
backend:
  name: github
  repo: joshglowgrid/friendly-message-oasis # You'll need to replace this
  branch: main
  auth_type: github-app
  app_id: ${GITHUB_APP_ID}
  private_key: ${GITHUB_PRIVATE_KEY}

local_backend: true # Enable local backend for development
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "SEO Title", name: "metaTitle", widget: "string"}
      - {label: "SEO Description", name: "metaDescription", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "SEO Title", name: "metaTitle", widget: "string"}
      - {label: "SEO Description", name: "metaDescription", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
