
backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "public/uploads" # Media files will be stored here
public_folder: "/uploads" # The src attribute for uploaded media

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "SEO Title", name: "title", widget: "string", required: false }
          - { label: "SEO Description", name: "description", widget: "text", required: false }
          - { label: "Canonical URL", name: "canonical", widget: "string", required: false }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "SEO Title", name: "title", widget: "string", required: false }
          - { label: "SEO Description", name: "description", widget: "text", required: false }
          - { label: "Canonical URL", name: "canonical", widget: "string", required: false }
