// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjdytrlpdjqtrosopqzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZHl0cmxwZGpxdHJvc29wcXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDE1MTksImV4cCI6MjA2MDYxNzUxOX0.ueTlv_iEBBifGelTuCcIUA66x11CAuqcp-vQf35jhRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);